# Generated by Django 6.0 on 2025-12-30 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.CharField()),
                ('B', models.CharField()),
                ('C', models.CharField()),
                ('D', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField()),
                ('Answer', models.CharField()),
                ('options', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exam.options')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.block')),
            ],
        ),
    ]
