# Generated by Django 6.0 on 2025-12-30 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='options',
            options={'verbose_name_plural': 'Options'},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='block',
        ),
        migrations.AddField(
            model_name='block',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='exam.subject'),
        ),
    ]
